/*CREATE TABLE IF NOT EXISTS MEMBER
(
    MEMBER_ID       INT PRIMARY KEY,
    MEMBER_NAME     VARCHAR(50) NULL,
    DELETE_FLAG     BIT
);*/
DROP TABLE IF EXISTS MEMBER_POINT;
CREATE TABLE IF NOT EXISTS MEMBER_POINT
(
    MEMBER_ID       INT PRIMARY KEY,
    POINT           INT,
    GET_COUNT       INT,
    CREATE_DATE     DATETIME,
    UPDATE_DATE     DATETIME,
    DELETE_FLAG     BIT
);

CREATE TABLE IF NOT EXISTS POINT
(
    POINT_ID        INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID       INT,
    POINT           INT,
    CREATE_DATE     DATETIME,
    UPDATE_DATE     DATETIME,
    DELETE_FLAG     BIT
);

DROP TABLE IF EXISTS REWARD;
CREATE TABLE IF NOT EXISTS REWARD
(
    REWARD_ID        INT PRIMARY KEY,
    SUBJECT          VARCHAR(50),
    CONTENT          TEXT,
    REWARD_TYPE      INT,
    REWARD_TYPE_NAME VARCHAR(10),
    CREATE_DATE      DATETIME,
    UPDATE_DATE      DATETIME,
    DELETE_FLAG      BIT
);

DROP TABLE IF EXISTS REWARD_DETAIL;
CREATE TABLE IF NOT EXISTS REWARD_DETAIL
(
    REWARD_DETAIL_ID INT PRIMARY KEY,
    REWARD_ID       INT,
    REWARD_COUNT    INT,
    QUANTITY        INT,
    MAX_CONTINUE    INT,
    CREATE_DATE     DATETIME,
    UPDATE_DATE     DATETIME,
    DELETE_FLAG     BIT
);

DROP TABLE IF EXISTS REWARD_ADDITIONAL;
CREATE TABLE IF NOT EXISTS REWARD_ADDITIONAL
(
    REWARD_ADDITIONAL_ID    INT PRIMARY KEY,
    REWARD_ID        INT,
    CONTINUE_DAY            INT,
    ADD_REWARD              INT,
    CREATE_DATE             DATETIME,
    UPDATE_DATE             DATETIME,
    DELETE_FLAG             BIT
);

/*
CREATE INDEX IDX_ORDER_ID ON ORDER_PRODUCT(ORDER_ID);

*/

